<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-IU0PMJ8" failures="2" tests="4" name="Test(failed)(failed)" time="3.137" errors="0" timestamp="2022-07-17T12:32:44 IST">
  <testcase classname="testng.failedtestmethod" name="m5" time="0.015">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testng.failedtestmethod.m5(failedtestmethod.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- m5 -->
  <testcase classname="testng.failedtestmethod" name="m3" time="0.004"/>
  <testcase classname="testng.failedtestmethod" name="m6" time="0.001"/>
  <testcase classname="testng.failedtestmethod" name="m4" time="3.018">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testng.failedtestmethod.m4() didn&amp;apos;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testng.failedtestmethod.m4() didn't finish within the time-out 3000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- m4 -->
  <testcase classname="testng.failedtestmethod" name="m2" time="0.0">
    <ignored/>
  </testcase> <!-- m2 -->
  <testcase classname="testng.failedtestmethod" name="m1" time="0.0">
    <ignored/>
  </testcase> <!-- m1 -->
</testsuite> <!-- Test(failed)(failed) -->
